language: node_js
node_js:
  - "node"
  - "8"
install:
  - npm install
script:
  - npm run lint
  - npm run build
# deploy:
#   skip_cleanup: true
#   provider: script
#   script: npm run deploy
#   on:
#     branch: master