language: node_js
node_js:
  - "node"
  - "8"
cache:
  directories:
    - node_modules/
install:
  - npm install
script:
  - npm run lint
  - npm run test:unit
  - npm run test:coveralls
  - npm run build
deploy:
  provider: script
  script: npm run deploy
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master$